spiderpig: Define `access_log_middleware` prior to `SessionMiddleware`
When the former middleware is added second, its attempt to get the user
session via `maybe_get_current_user` will result in the following error.

    AssertionError: SessionMiddleware must be installed to access
    request.session

Define `access_log_middleware` first so it can reliably access the
request session.

Change-Id: Ib064dd7fb17a111207a53461ae4a725e3c018428