Improve error reporting for bad configuration setting syntax
Before:
debian@deploy:/srv$ scap prep -Dwmf_realm=labs -Dstage_dir=/srv/mediawiki-labs auto
WARNING:prep:Unhandled error (Application._handle_exception):
Traceback (most recent call last):
  File "/workspace/scap/scap/cli.py", line 351, in run
    app._load_config()
  File "/workspace/scap/scap/cli.py", line 193, in _load_config
    defines = dict(self.arguments.defines)
ValueError: dictionary update sequence element #0 has length 1; 2 is required
ERROR:prep:prep failed: <ValueError> dictionary update sequence element #0 has length 1; 2 is required

After:
debian@deploy:/srv$ scap prep -Dwmf_realm=labs -Dstage_dir=/srv/mediawiki-labs auto
Invalid configuration setting: wmf_realm=labs
Settings must be in 'key:value' format

Change-Id: I8787586ed9b8d8eeea261322d6635359735e8e25