Quietly commit everything
Summary:
Git puts '%' in its commit output and since we pass that to a logger
scap freaks out a little:

    TypeError: error: (not enough arguments for format string); format
    string: (rewrite
    php-master/extensions/ConfirmEdit/ReCaptcha/i18n/bs.json (78%));
    arguments: (())

This will suppress that particular output.

Reviewers: mmodell, dduvall, demon, #release-engineering-team

Reviewed By: demon, #release-engineering-team

Tags: #release-engineering-team

Differential Revision: https://phabricator.wikimedia.org/D633