Error: --service-restart without a service_name
Summary:
If you use the flag `--service-restart` chances are you expect there to
be a service configured that scap is supposed to restart. Scap should be
helpful here and stop you before you get too far.

Bug: T207263

Reviewers: mmodell, mobrovac, #release-engineering-team

Reviewed By: mobrovac

Tags: #release-engineering-team

Differential Revision: https://phabricator.wikimedia.org/D1118