Update patch set 2
Patch Set 2:

Zuul can not merge the file. From the /var/log/zuul/debug.log on gallium:

 2014-03-05 02:00:13,769 DEBUG zuul.IndependentPipelineManager: Preparing ref for: <Change 0x7f6a20d0ed10 116918,2>
 2014-03-05 02:00:13,769 INFO zuul.IndependentPipelineManager: Change <Change 0x7f6a20d0ed10 116918,2> depends on changes []
 2014-03-05 02:00:13,770 DEBUG zuul.Repo: Resetting repository /srv/ssd/zuul/git/mediawiki/tools/scap
 2014-03-05 02:00:13,770 DEBUG zuul.Repo: Updating repository /srv/ssd/zuul/git/mediawiki/tools/scap
 2014-03-05 02:00:13,895 DEBUG zuul.Repo: Checking out master
 2014-03-05 02:00:14,095 DEBUG zuul.Repo: Merging refs/changes/18/116918/2 with args ['-s', 'resolve', 'FETCH_HEAD']
 2014-03-05 02:00:14,140 DEBUG zuul.Merger: Unable to merge <Change 0x7f6a20d0ed10 116918,2>
 Traceback (most recent call last):
   File "/usr/local/lib/python2.7/dist-packages/zuul/merger.py", line 206, in _mergeChange
     repo.merge(change.refspec, 'resolve')
   File "/usr/local/lib/python2.7/dist-packages/zuul/merger.py", line 99, in merge
     self.repo.git.merge(*args)
   File "/usr/lib/pymodules/python2.7/git/cmd.py", line 227, in <lambda>
     return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)
   File "/usr/lib/pymodules/python2.7/git/cmd.py", line 456, in _call_process
     return self.execute(call, **_kwargs)
   File "/usr/lib/pymodules/python2.7/git/cmd.py", line 377, in execute
     raise GitCommandError(command, status, stderr_value)
 GitCommandError: 'git merge -s resolve FETCH_HEAD' returned exit status 1: error: Merge requires file-level merging
fatal: merge program failed
 2014-03-05 02:00:14,141 INFO zuul.IndependentPipelineManager: Unable to merge change <Change 0x7f6a20d0ed10 116918,2>


Ie it can't merge it with the tip of the master branch :-(  Trying to merge manually yields a conflict in bin/sync-wikiversions

Patch-set: 2