Update patch set 5
Patch Set 5:

This broke things during the deployment today.

ValueError: /srv/mediawiki-staging/php-1.25wmf20/tests/parser/parserTests.txt has content before opening
<ValueError> /srv/mediawiki-staging/php-1.25wmf20/extensions/Scribunto/engines/LuaCommon/lualib/ustring/make-tables.php has content before opening <?php tag

Patch-set: 5
Reviewer: Alex Monk <98@e9e9afe9-4712-486d-8885-f54b72dd1951>
Label: Verified=0