scap deploy: misc tweaks
* The --repo argument to "scap deploy-local" appears to be required
  (self.arguments.repo is accessed unconditionally (expecting a
  string) in deploy.py), so add required=True to its definition.

* _get_remote_overrides(): Generate a clearer error message when
  retrieving the remote configuration fails.  This is achieved by
  using raise_for_status() on the response object.  This will generate
  a decent error message containing the URL that was accessed, and the
  HTTP response code.

  Before:
  FileNotFoundError: [Errno 2] Config file not found: 'deploy/restbase/deploy/.git/DEPLOY_HEAD'

  which deceivingly makes it look like a local file is being accessed.

  After:
  requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://deploy/restbase/deploy/.git/DEPLOY_HEAD

Change-Id: If9d185f0f1d0dc766eae35a419bf40878d7e4200