Update patch set 4
Patch Set 4: Code-Review-1

7:32:28 Unhandled error:
Traceback (most recent call last):
  File "/mnt/srv/deployment/scap/scap/scap/cli.py", line 266, in run
    exit_status = app.main(extra_args)
  File "/mnt/srv/deployment/scap/scap/scap/main.py", line 65, in main
    self._after_cluster_sync()
  File "/mnt/srv/deployment/scap/scap/scap/main.py", line 250, in _after_cluster_sync
    succeeded, failed = restart_hhvm.run()
ValueError: too many values to unpack
17:32:28 scap failed: ValueError too many values to unpack (duration: 00m 47s)


When Job.run is called without a reporter it returns "List of (host, status, output) tuples" rather than the "(success, fail)" tuple that it returns when a reporter is used. The easiest fix would be to change to `restart_hhvm.progress('hhvm_restart').run()` which will also give a progress meter for the restart sub-process.

Patch-set: 4
Label: Code-Review=-1