scap prep: Fix version_parser
scap/plugins/prep.py:
  version_parser():
    The original code assumed that re.match would throw re.error if
    the supplied string did not match the regexp, but that's not what
    happens.  re.match returns None if no match.

Before:

$ scap prep xyzzy
10:54:37 WARNING  - Unhandled error:
Traceback (most recent call last):
...
AttributeError: 'NoneType' object has no attribute 'group'
10:54:37 ERROR    - scap failed: <AttributeError> 'NoneType' object has no attribute 'group'

After:

$ scap prep xyzzy
usage: scap prep [-h] [--conf CONF_FILE] [--no-shared-authsock] [-D <name>:<value>] [-v] [--environment ENVIRONMENT] [--no-log-message] [-p PREFIX] BRANCH
scap prep: error: argument BRANCH: Branch 'xyzzy' does not match required format

Bug: T259706
Change-Id: Ifa587f2296c0d35e4b608a1c8dbc7f000a46bc83