Backport.vue: Remove unnecessary {{ item.text }}
The `text` attribute of `item` is not defined, so `{{ item.text }}`
doesn't actually do anything but generate the following linter error:

```
Property 'text' does not exist on type 'ListItem<any>'.  ts-plugin(2339)
```

Bug: T392508
Change-Id: I18fb246b0300169f5342f14ebfde8d1b6a821e94