scap deploy-promote: Make idempotent
_create_version_update_patch: If the requested promotion produced no
changes to the wikiversions file or php symlink, don't push try to
push to gerrit.  Pushing to gerrit under that those circumstances
results in an error like the following:

remote:
remote: Processing changes: refs: 1
remote: Processing changes: refs: 1, done
To ssh://gerrit.traindev:29418/operations/mediawiki-config
 ! [remote rejected]     HEAD -> refs/for/train-dev%topic=1.38.0-wmf.25,l=Code-Review+2 (no new changes)
error: failed to push some refs to 'ssh://traindev@gerrit.traindev:29418/operations/mediawiki-config'

Change-Id: I466d2d9e9e5c87fcc480eafb1d3036a275fd9a64